server:
  port:  80
spring:
  datasource:
    password: password
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/spring?useSSL=false&serverTimezone=UTC
